agents:
  index: '代理商-列表'
  new: '代理商-申请界面'
  create: '代理商-申请'
  show: '代理商-详情'
audits:
  index: '审批-操作台'
  projects: '审批-立项'
  orders: '审批-样品礼品'
  bargains: '审批-特价'
  agents: '审批-代理商'
  audits: '审批-我的审批记录'
  success: '审批-通过'
  failed_notice: '审批-打回界面'
  failed: '审批-打回'
  invoices: '审批-开票'
  invoice_success: '审批-开票确认'
competitors:
  index: '竞品信息-列表'
  new: '竞品信息-上传界面'
  create: '竞品信息-上传'
  edit: '竞品信息-编辑界面'
  update: '竞品信息-编辑'
  destroy: '竞品信息-删除'
trains:
  index: '培训资料-列表'
  new: '培训资料-上传界面'
  create: '培训资料-上传'
  edit: '培训资料-编辑界面'
  update: '培训资料-编辑'
  destroy: '培训资料-删除'
contracts:
  index: '战略合同-列表'
  new: '战略合同-新建界面'
  create: '战略合同-新建'
  edit: '战略合同-编辑界面'
  update: '战略合同-编辑'
  show: '战略合同-详情'
costs:
  index: '费用-列表'
  new: '费用-新建界面'
  create: '费用-新建'
  edit: '费用-编辑界面'
  update: '费用-编辑'
  destroy: '费用-删除'
invoices:
  new: '开票-新建界面'
  create: '开票-新建'
  edit: '开票-编辑界面'
  update: '开票-编辑'
  show: '开票-详情'
  invoice_apply: '开票-申请'
  index: '开票-列表'
manage_orders:
  index: '订单管理-列表'
  deliver: '订单管理-发货'
  show: '订单-详情'
  edit_payment: '订单-录入进度款界面'
  update_payment: '订单-录入进度款'
  deliver_message: '订单-提醒收货界面'
  send_message: '订单-提醒收货'
  payment_logs: '订单-查看回款记录'
  edit_deliver: '订单-录入发货款界面'
  update_deliver: '订单-录入发货款'
  deliver_logs: '订单-查看发货款记录'
manage_invoices:
  index: '开票管理-列表'
  upload_file: '开票管理-上传票据'
notices:
  index: '消息通知-列表'
  check: '消息通知-标记'
orders:
  new: '订单-添加商品界面'
  create: '订单-添加商品'
  edit: '订单-编辑商品界面'
  update: '订单-编辑商品'
  destroy: '订单-删除商品'
  apply_order: '订单-申请'
  place_order: '订单-下单'
products:
  index: '产品-列表'
  new: '产品-新建界面'
  create: '产品-新建'
  edit: '产品-编辑界面'
  update: '产品-编辑'
  show: '产品-详情'
  contract_sales: '产品-合同价'
  import: '产品-批量导入界面'
  do_import: '产品-批量导入'
projects:
  index: '项目-列表'
  new: '项目-立项界面'
  create: '项目-立项'
  show: '项目-详情'
  update_agency: '项目动态-选择操作模式'
  edit_information: '项目-添加项目资料界面'
  update_information: '项目-添加项目资料'
  upload: '项目动态-上传文件资料'
  delete_attachment: '项目动态-删除项目资料'
  payment: '项目动态-回款金额确认'
  step_event: '项目动态-下一步'
  agent: '项目-代理商'
  report: '项目-报备'
  sales: '项目-价格体系'
  order_import: '项目-批量订单界面'
  do_import: '项目-批量导入订单'
  show_money: '项目-查看金额'
reports:
  new: '项目报备-新建界面'
  create: '项目报备-新建'
  edit: '项目报备-编辑界面'
  update: '项目报备-编辑'
sales:
  new: '价格体系-新建界面'
  create: '价格体系-新建'
  edit: '价格体系-编辑界面'
  update: '价格体系-编辑'
  destroy: '价格体系-删除'
  show: '价格体系-详情'
record_reports:
  index: '报表-今日看板'
  projects: '报表-项目'
  orders: '报表-订单'
  invoices: '报表-开票'
  users: '报表-人员业绩'
  costs: '报表-费用'
  products: '报表-产品'





